package com.intellij.jira.rest.model;

public enum JiraPermissionType {
    BROWSE_PROJECTS("BROWSE_PROJECTS"),
    CREATE_ISSUES("CREATE_ISSUES"),
    EDIT_ISSUES("EDIT_ISSUE"),
    TRANSITION_ISSUES("TRANSITION_ISSUE"),
    ADD_COMMENTS("COMMENT_ISSUE"),
    EDIT_ALL_COMMENTS("COMMENT_EDIT_ALL"),
    EDIT_OWN_COMMENTS("COMMENT_EDIT_OWN"),
    DELETE_ALL_COMMENTS("COMMENT_DELETE_ALL"),
    DELETE_OWN_COMMENTS("COMMENT_DELETE_OWN"),
    LINK_ISSUES("LINK_ISSUE"),
    WORK_ON_ISSUES("WORK_ISSUE"),
    EDIT_ALL_WORKLOGS("WORKLOG_EDIT_ALL"),
    EDIT_OWN_WORKLOGS("WORKLOG_EDIT_OWN"),
    DELETE_ALL_WORKLOGS("WORKLOG_DELETE_ALL"),
    DELETE_OWN_WORKLOGS("WORKLOG_DELETE_OWN"),
    MANAGE_WATCHERS("MANAGE_WATCHER_LIST"),
    CREATE_ATTACHMENTS("CREATE_ATTACHMENT"),
    DELETE_ALL_ATTACHMENTS("ATTACHMENT_DELETE_ALL"),
    DELETE_OWN_ATTACHMENTS("ATTACHMENT_DELETE_OWN");

    private String oldPermission;

    JiraPermissionType(String oldPermission) {
        this.oldPermission = oldPermission;
    }

    public String getOldPermission() {
        return oldPermission;
    }

}
